#!/usr/bin/env python3
"""Gerrit stream-events watcher → triggers Jenkins build, posts Verified vote."""

import json
import subprocess
import sys
import time
import os
import threading
import urllib.request
from base64 import b64encode

# All settings overridable via RC_* environment variables (e.g. after a port
# migration, restart the watcher with RC_GERRIT_PORT=NNNN — no code change).
GERRIT_HOST = os.environ.get("RC_GERRIT_HOST", "localhost")
GERRIT_PORT = os.environ.get("RC_GERRIT_PORT", "19418")
GERRIT_USER = os.environ.get("RC_GERRIT_USER", "ci")
SSH_KEY = os.environ.get("RC_SSH_KEY", os.path.expanduser("~/.ssh/ci_gerrit_key"))
JENKINS_URL = os.environ.get("RC_JENKINS_URL", "http://localhost:18090")
JENKINS_JOB = os.environ.get("RC_JENKINS_JOB", "raycaster-ci")
JENKINS_USER = os.environ.get("RC_JENKINS_USER", "admin")
# Read from secrets file
ADMIN_PASS_FILE = os.environ.get(
    "RC_ADMIN_PASS_FILE", "/opt/jenkins/home/secrets/initialAdminPassword"
)

PROJECT_PATTERN = os.environ.get("RC_GERRIT_PROJECT", "raycaster-demo")  # exact match

JENKINS_CLI = "/tmp/jenkins-cli.jar"

def read_admin_pass():
    try:
        with open(ADMIN_PASS_FILE) as f:
            return f.read().strip()
    except Exception:
        return None

def trigger_jenkins(change_num, patchset_num, revision, refspec, branch, event_type):
    """Trigger Jenkins build via CLI (avoids CSRF issues).
    Returns the build URL on success, None on failure."""
    admin_pass = read_admin_pass()
    if not admin_pass:
        print("ERROR: Cannot read admin password", file=sys.stderr)
        return None

    params = [
        f"GERRIT_CHANGE_NUMBER={change_num}",
        f"GERRIT_PATCHSET_NUMBER={patchset_num}",
        f"GERRIT_PATCHSET_REVISION={revision}",
        f"GERRIT_REFSPEC={refspec}",
        f"GERRIT_BRANCH={branch}",
        f"GERRIT_EVENT_TYPE={event_type}",
    ]
    cmd = [
        "java", "-jar", JENKINS_CLI,
        "-s", JENKINS_URL,
        "-auth", f"{JENKINS_USER}:{admin_pass}",
        "build", JENKINS_JOB,
        "-w",
    ]
    for p in params:
        cmd.extend(["-p", p])

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        if result.returncode == 0:
            cli_out = result.stdout.strip()
            print(f"Jenkins triggered: {cli_out}")
            # Parse "Started flowhub-ci #N" to build URL
            import re
            m = re.search(r'#(\d+)', cli_out)
            if m:
                return f"{JENKINS_URL}/job/{JENKINS_JOB}/{m.group(1)}"
            return f"{JENKINS_URL}/job/{JENKINS_JOB}"
        else:
            print(f"Jenkins trigger failed: {result.stderr.strip()}", file=sys.stderr)
            return None
    except Exception as e:
        print(f"Jenkins trigger error: {e}", file=sys.stderr)
        return None

def post_verified(change_num, patchset_num, verified_value, message):
    """Post Verified vote and optional comment to Gerrit via SSH.
    Uses single-string remote command to properly escape message with spaces."""
    gerrit_cmd = f"gerrit review {change_num},{patchset_num} --verified {verified_value}"
    if message:
        escaped_msg = message.replace("'", "'\\''")
        gerrit_cmd += f" --message '{escaped_msg}'"
    gerrit_cmd += " --tag autogenerated:gerrit-event-watcher"

    cmd = [
        "ssh", "-p", GERRIT_PORT, "-i", SSH_KEY,
        f"{GERRIT_USER}@{GERRIT_HOST}",
        gerrit_cmd,
    ]
    try:
        subprocess.run(cmd, check=True, capture_output=True, timeout=30)
        print(f"Verified {verified_value} posted for {change_num},{patchset_num}")
    except subprocess.CalledProcessError as e:
        print(f"Failed to post vote: {e.stderr.decode() if e.stderr else e}", file=sys.stderr)
    except Exception as e:
        print(f"Vote error: {e}", file=sys.stderr)

def handle_event(event):
    """Process a single Gerrit stream event."""
    etype = event.get("type", "")
    change = event.get("change", {})
    project = change.get("project", "")
    if project != PROJECT_PATTERN:
        return

    change_num = change.get("number", "")
    branch = change.get("branch", "")
    patchset = event.get("patchSet", {})
    patchset_num = patchset.get("number", "")
    revision = patchset.get("revision", "")
    refspec = patchset.get("ref", "")

    should_trigger = False
    trigger_reason = ""

    if etype == "patchset-created":
        should_trigger = True
        trigger_reason = "patchset-created"
    elif etype == "comment-added":
        comment = event.get("comment", "")
        if "recheck" in comment.lower():
            should_trigger = True
            trigger_reason = "recheck"

    if should_trigger:
        print(f"Triggering build for {change_num},{patchset_num} ({trigger_reason})")
        build_url = trigger_jenkins(change_num, patchset_num, revision, refspec, branch, etype)
        if build_url:
            msg = f"Build Started {build_url}"
            post_verified(change_num, patchset_num, 0, msg)
            # Poll build result in background
            t = threading.Thread(
                target=poll_build_result,
                args=(build_url, change_num, patchset_num),
                daemon=True,
            )
            t.start()

def get_jenkins_api(path):
    """Call Jenkins REST API, return parsed JSON."""
    admin_pass = read_admin_pass()
    if not admin_pass:
        return None
    auth_str = b64encode(f"{JENKINS_USER}:{admin_pass}".encode()).decode()
    req = urllib.request.Request(f"{JENKINS_URL}{path}")
    req.add_header("Authorization", f"Basic {auth_str}")
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read())
    except Exception as e:
        print(f"Jenkins API error: {e}", file=sys.stderr)
        return None

def poll_build_result(build_url, change_num, patchset_num):
    """Poll Jenkins build until completion, then post final Verified vote."""
    # Extract job name and build number from URL
    # URL: http://localhost:18090/job/raycaster-ci/123
    parts = build_url.rstrip("/").split("/")
    build_num = parts[-1]
    job_name = parts[-2]
    api_path = f"/job/{job_name}/{build_num}/api/json"

    for _ in range(120):  # poll up to 10 minutes
        time.sleep(5)
        data = get_jenkins_api(api_path)
        if not data:
            continue
        result = data.get("result")
        if result:  # SUCCESS, FAILURE, UNSTABLE, ABORTED
            vote = 1 if result == "SUCCESS" else -1
            msg = f"Build {result} {build_url}"
            post_verified(change_num, patchset_num, vote, msg)
            print(f"Build {build_num} finished: {result}, Verified {vote}")
            return
    print(f"Build {build_num} timed out waiting for result", file=sys.stderr)

def stream_events():
    """Run gerrit stream-events and process events. Auto-reconnect on failure."""
    cmd = [
        "ssh", "-p", GERRIT_PORT, "-i", SSH_KEY,
        "-o", "ServerAliveInterval=30",
        "-o", "ServerAliveCountMax=3",
        f"{GERRIT_USER}@{GERRIT_HOST}",
        "gerrit", "stream-events",
    ]

    while True:
        print(f"Connecting to Gerrit stream-events...")
        try:
            proc = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
            for line in proc.stdout:
                line = line.strip()
                if not line:
                    continue
                try:
                    event = json.loads(line)
                    handle_event(event)
                except json.JSONDecodeError:
                    print(f"Non-JSON output: {line[:200]}", file=sys.stderr)

            rc = proc.wait()
            print(f"stream-events exited with code {rc}, reconnecting in 5s...")
        except Exception as e:
            print(f"Connection error: {e}, reconnecting in 5s...", file=sys.stderr)

        time.sleep(5)

if __name__ == "__main__":
    stream_events()
