#!/usr/bin/env python3
"""Generate src/generated/MapData.hpp from a .map text file.

Usage:
    python3 scripts/mapgen.py                # use default paths
    python3 scripts/mapgen.py --input my.map # override input only
"""
import argparse
import os
import sys
from pathlib import Path

WIDTH = 24
HEIGHT = 24

SYMBOLS = {
    '.': 0,  # Empty
    '#': 1,  # Brick
    'S': 2,  # Stone
}


def parse_map(text):
    """Parse .map file. Math coordinates: y=0 at bottom, y increases upward.
    File top = y max (game top), file bottom = y=0 (game bottom).
    Returns rows in C++ array order: array[0] = y=0 (bottom).
    """
    grid = []
    for lineno, raw in enumerate(text.splitlines(), 1):
        if lineno == 1 and raw.startswith('\ufeff'):
            raw = raw[1:]
        line = raw.split('//', 1)[0].rstrip('\r\n')
        if not line.strip():
            continue
        stripped = line.lstrip()
        # Column header row: all digits, no spaces
        if stripped and stripped[0].isdigit() and ' ' not in stripped:
            continue
        # Data row: "NN <24 chars>" — strip row number prefix
        parts = line.split(None, 1)
        if len(parts) == 2 and parts[0].isdigit() and len(parts[1]) >= WIDTH:
            row_str = parts[1][:WIDTH]
        else:
            row_str = line.strip()[:WIDTH]
        if len(row_str) != WIDTH:
            raise ValueError(
                "line %d: expected %d chars, got %d: %r"
                % (lineno, WIDTH, len(row_str), row_str)
            )
        row = []
        for col, ch in enumerate(row_str):
            if ch not in SYMBOLS:
                raise ValueError(
                    "line %d, col %d: invalid char %r" % (lineno, col + 1, ch)
                )
            row.append(SYMBOLS[ch])
        grid.append(row)
    if len(grid) != HEIGHT:
        raise ValueError("map has %d rows, expected %d" % (len(grid), HEIGHT))
    # File top = y max -> array[last]; file bottom = y=0 -> array[0]
    return list(reversed(grid))


def generate_header(rows, map_path):
    lines = []
    lines.append(f"// Generated by scripts/mapgen.py from {map_path}. DO NOT EDIT.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("// WallType is defined in core/Map.hpp; values match WallType underlying.")
    lines.append("")
    lines.append("namespace ray {")
    lines.append("")
    lines.append(f"constexpr int kMapWidth = {WIDTH};")
    lines.append(f"constexpr int kMapHeight = {HEIGHT};")
    lines.append("")
    lines.append("// row 0 = scene top (world y = kMapHeight - 1)")
    lines.append("// NOLINTBEGIN(cppcoreguidelines-avoid-c-arrays, modernize-avoid-c-arrays)")
    lines.append(
        "constexpr uint8_t kTiles[kMapHeight][kMapWidth] = {"
    )
    for row in rows:
        vals = ", ".join(str(v) for v in row)
        lines.append(f"    {{ {vals} }},")
    lines.append("};")
    lines.append("// NOLINTEND(cppcoreguidelines-avoid-c-arrays, modernize-avoid-c-arrays)")
    lines.append("")
    lines.append("} // namespace ray")
    lines.append("")
    return "\n".join(lines)


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
DEFAULT_INPUT = PROJECT_ROOT / "tools" / "maps" / "default.map"
DEFAULT_OUTPUT = PROJECT_ROOT / "src" / "generated" / "MapData.hpp"


def main():
    parser = argparse.ArgumentParser(description="Generate MapData.hpp from .map file")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT, help="Path to .map file")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Path to output MapData.hpp")
    args = parser.parse_args()

    if not os.path.isfile(args.input):
        print(f"error: input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    with open(args.input, "r", encoding="utf-8") as f:
        text = f.read()

    try:
        rows = parse_map(text)
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        sys.exit(1)

    header = generate_header(rows, args.input)

    os.makedirs(args.output.parent, exist_ok=True)

    if args.output.exists():
        args.output.unlink()

    tmp = args.output.with_suffix(args.output.suffix + ".tmp")
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(header)
    os.replace(tmp, args.output)

    print(f"Generated {args.output} from {args.input}")


if __name__ == "__main__":
    main()
